# -*- coding: utf-8 -*-
"""2022-1-60-029_NN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oummTsw-il5ulM-TvYjFgvCtPlOzRJ3k

# Connect to the drive
"""

from google.colab import drive
drive.mount('/content/drive')

"""# Important Libraries"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import matplotlib.pyplot as plt

"""# Read the dataset"""

df = pd.read_csv('/content/drive/MyDrive/CSE 475 ML/LAB_06_NeuralNetwork/Placement_Data_Full_Class.csv')
df

""" # EDA"""

df.head()

df.isnull().sum()

"""# Null values adjusted by mode value of the salary"""

mode_value = df['salary'].mode()[0]
df['salary'] = df['salary'].fillna(mode_value)

df.isnull().sum()

df.info()

df_copy = df.copy()

"""# Mapping"""

gender_mapping = {
    'M': 1,
    'F': 2,
}
df['gender'] = df['gender'].map(gender_mapping)

ssc_b_mapping = {
    'Others': 1,
    'Central': 2,
}
df['ssc_b'] = df['ssc_b'].map(ssc_b_mapping)

hsc_b_mapping = {
    'Others': 1,
    'Central': 2,
}
df['hsc_b'] = df['hsc_b'].map(hsc_b_mapping)

hsc_s_mapping = {
    'Commerce': 1,
    'Science': 2,
    'Arts': 3,
}
df['hsc_s'] = df['hsc_s'].map(hsc_s_mapping)

degree_t_mapping = {
    'Comm&Mgmt': 1,
    'Others': 2,
    'Sci&Tech': 3,
    'Others': 4,
}
df['degree_t'] = df['degree_t'].map(degree_t_mapping)

workex_mapping = {
    'No': 1,
    'Yes': 2,
}
df['workex'] = df['workex'].map(workex_mapping)

specialisation_mapping = {
    'Mkt&HR': 1,
    'Mkt&Fin': 2,
}
df['specialisation'] = df['specialisation'].map(specialisation_mapping)

status_mapping = {
    'Not Placed': 1,
    'Placed': 2,
}
df['status'] = df['status'].map(status_mapping)

"""# Drop 'sl_no' and any irrelevant columns"""

df = df.drop(['sl_no', 'salary'], axis=1)

# Separate features and target
X = df.drop("status", axis=1)
y = df["status"]

# Scale the features
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

"""# Build the vanilla neural network"""

model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(16, activation='relu'),
    Dense(8, activation='relu'),
    Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

"""# Step 5: Train the model"""

history = model.fit(X_train, y_train, epochs=250, batch_size=8, validation_split=0.2)

"""# Step 6: Evaluate the model"""

loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {accuracy:.4f}")

"""#Plot loss and accuracy curves"""

plt.figure(figsize=(12, 5))

# Loss plot
plt.subplot(1, 2, 1)
plt.plot(history.history['loss'], label='Training Loss', color='blue')
plt.plot(history.history['val_loss'], label='Validation Loss', color='orange')
plt.title('Loss Curve')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()

# Accuracy plot
plt.subplot(1, 2, 2)
plt.plot(history.history['accuracy'], label='Training Accuracy', color='green')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy', color='red')
plt.title('Accuracy Curve')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()

plt.tight_layout()
plt.show()

"""# **Try to another technique to increase the accuracy:**

# Install necessary libraries
# pip install tensorflow matplotlib
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
import tensorflow as tf
from tensorflow.keras import layers, models
import matplotlib.pyplot as plt

data = pd.read_csv('/content/drive/MyDrive/CSE 475 ML/LAB_06_NeuralNetwork/Placement_Data_Full_Class.csv')

"""# Drop irrelevant columns"""

data = data.drop(['sl_no', 'salary'], axis=1)

"""# Encode categorical features"""

label_encoders = {}
categorical_cols = ['gender', 'ssc_b', 'hsc_b', 'hsc_s', 'degree_t', 'workex', 'specialisation', 'status']

for col in categorical_cols:
    le = LabelEncoder()
    data[col] = le.fit_transform(data[col])
    label_encoders[col] = le

"""# Separate features and target"""

X = data.drop('status', axis=1)
y = data['status']

"""# Scale features"""

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

"""# Train-test split"""

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

"""# ----------------- Vanilla Neural Network -----------------"""

vanilla_model = models.Sequential([
    layers.Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    layers.Dense(32, activation='relu'),
    layers.Dense(1, activation='sigmoid')
])

vanilla_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

"""# Train Vanilla NN"""

vanilla_history = vanilla_model.fit(X_train, y_train, epochs=50, batch_size=8, validation_data=(X_test, y_test))

"""# ----------------- Plotting Results -----------------

# Vanilla Neural Network Plots
"""

plt.figure(figsize=(14,6))

plt.subplot(1,2,1)
plt.plot(vanilla_history.history['accuracy'], label='Train Accuracy')
plt.plot(vanilla_history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Vanilla Neural Network - Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

plt.subplot(1,2,2)
plt.plot(vanilla_history.history['loss'], label='Train Loss')
plt.plot(vanilla_history.history['val_loss'], label='Validation Loss')
plt.title('Vanilla Neural Network - Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.tight_layout()
plt.show()

"""# ----------------- CNN for Tabular Data -----------------"""

cnn_model = models.Sequential([
    layers.Reshape((X_train.shape[1], 1), input_shape=(X_train.shape[1],)),
    layers.Conv1D(32, kernel_size=2, activation='relu'),
    layers.MaxPooling1D(pool_size=2),
    layers.Flatten(),
    layers.Dense(32, activation='relu'),
    layers.Dense(1, activation='sigmoid')
])

cnn_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

"""# Train CNN"""

cnn_history = cnn_model.fit(X_train, y_train, epochs=50, batch_size=8, validation_data=(X_test, y_test))

"""# CNN Model Plots"""

plt.figure(figsize=(14,6))

plt.subplot(1,2,1)
plt.plot(cnn_history.history['accuracy'], label='Train Accuracy')
plt.plot(cnn_history.history['val_accuracy'], label='Validation Accuracy')
plt.title('CNN Model - Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

plt.subplot(1,2,2)
plt.plot(cnn_history.history['loss'], label='Train Loss')
plt.plot(cnn_history.history['val_loss'], label='Validation Loss')
plt.title('CNN Model - Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.tight_layout()
plt.show()

"""# ----------------- Final Evaluation -----------------"""

vanilla_loss, vanilla_accuracy = vanilla_model.evaluate(X_test, y_test)
cnn_loss, cnn_accuracy = cnn_model.evaluate(X_test, y_test)

print(f"\nFinal Test Accuracy of Vanilla Neural Network: {vanilla_accuracy:.4f}")
print(f"Final Test Accuracy of CNN Model: {cnn_accuracy:.4f}")

"""# Generalize Vanilla NN + CNN:"""

from tensorflow.keras import regularizers
from tensorflow.keras.callbacks import EarlyStopping

"""# Early stopping callback"""

early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

"""# ----Generalized Vanilla Neural Network ------"""

vanilla_model = models.Sequential([
    layers.Dense(32, activation='relu', input_shape=(X_train.shape[1],),
                 kernel_regularizer=regularizers.l2(0.01)),
    layers.Dropout(0.5),
    layers.Dense(16, activation='relu', kernel_regularizer=regularizers.l2(0.01)),
    layers.Dropout(0.5),
    layers.Dense(1, activation='sigmoid')
])

vanilla_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

"""# Train Vanilla NN with early stopping"""

vanilla_history = vanilla_model.fit(X_train, y_train, epochs=100, batch_size=8,
                                    validation_data=(X_test, y_test),
                                    callbacks=[early_stop])

plt.figure(figsize=(14,6))

plt.subplot(1,2,1)
plt.plot(vanilla_history.history['accuracy'], label='Train Accuracy')
plt.plot(vanilla_history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Generalized Vanilla Neural Network - Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

plt.subplot(1,2,2)
plt.plot(vanilla_history.history['loss'], label='Train Loss')
plt.plot(vanilla_history.history['val_loss'], label='Validation Loss')
plt.title('Generalized Vanilla Neural Network - Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.tight_layout()
plt.show()

"""# ----- Generalized CNN for Tabular Data -------"""

cnn_model = models.Sequential([
    layers.Reshape((X_train.shape[1], 1), input_shape=(X_train.shape[1],)),
    layers.Conv1D(16, kernel_size=2, activation='relu', kernel_regularizer=regularizers.l2(0.01)),
    layers.MaxPooling1D(pool_size=2),
    layers.Flatten(),
    layers.Dense(16, activation='relu', kernel_regularizer=regularizers.l2(0.01)),
    layers.Dropout(0.5),
    layers.Dense(1, activation='sigmoid')
])

cnn_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

"""# Train CNN with early stopping"""

cnn_history = cnn_model.fit(X_train, y_train, epochs=100, batch_size=8,
                            validation_data=(X_test, y_test),
                            callbacks=[early_stop])

plt.figure(figsize=(14,6))

plt.subplot(1,2,1)
plt.plot(cnn_history.history['accuracy'], label='Train Accuracy')
plt.plot(cnn_history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Generalized CNN Model - Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

plt.subplot(1,2,2)
plt.plot(cnn_history.history['loss'], label='Train Loss')
plt.plot(cnn_history.history['val_loss'], label='Validation Loss')
plt.title('Generalized CNN Model - Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.tight_layout()
plt.show()

"""# ------- Final Evaluation ------"""

vanilla_loss, vanilla_accuracy = vanilla_model.evaluate(X_test, y_test)
cnn_loss, cnn_accuracy = cnn_model.evaluate(X_test, y_test)

print(f"\n✅ Final Test Accuracy of Generalized Vanilla Neural Network: {vanilla_accuracy:.4f}")
print(f"✅ Final Test Accuracy of Generalized CNN Model: {cnn_accuracy:.4f}")

"""# After applying generalization techniques (Dropout, L2 regularization, EarlyStopping), the CNN model showed notable improvement, increasing its final test accuracy from 79.07% to 83.72%.
# The Vanilla Neural Network maintained the same test accuracy (86.05%) but achieved greater model stability with reduced overfitting.    
# **Vanilla Neural Network:**
# Accuracy stayed the same (86.05%),
# BUT training became much more stable — less risk of overfitting now.
# **CNN:**
# Improved significantly from 79.07% → 83.72%
# Overfitting was reduced, validation accuracy became much closer to training accuracy.
"""